# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Dialog(QtWidgets.QDialog):
    def __init__(self):
        super(Dialog, self).__init__()
        self.selected_row = None

    def setup_ui(self, Dialog, doctor_list, search):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.button_box = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.button_box.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.button_box.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.button_box.setObjectName("button_box")
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.button_box.accepted.connect(self.select_row_num)
        self.button_box.accepted.connect(Dialog.reject)

        self.scroll_area = QtWidgets.QScrollArea(parent=Dialog)
        self.scroll_area.setGeometry(QtCore.QRect(30, 40, 341, 191))
        self.scroll_area.setWidgetResizable(True)
        self.scroll_area.setObjectName("scroll_area")

        self.scroll_area_contents = QtWidgets.QWidget()
        self.scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 339, 189))
        self.scroll_area_contents.setObjectName("scroll_area_contents")

        self.list_widget = QtWidgets.QListWidget(parent=self.scroll_area_contents)
        self.list_widget.setGeometry(QtCore.QRect(0, 0, 341, 192))
        self.list_widget.setObjectName("list_widget")

        self.scroll_area.setWidget(self.scroll_area_contents)

        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 20, 341, 16))
        self.label.setObjectName("label")

        for item in doctor_list:
            self.list_widget.addItem(item.get_name())

        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", f"Search Results for \"{search}\""))
        self.button_box.accepted.connect(Dialog.accept)  # type: ignore
        self.button_box.rejected.connect(Dialog.reject)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def select_row_num(self):
        self.selected_row = self.list_widget.currentRow()

    def get_selected_row(self):
        return self.selected_row
