# Form implementation generated from reading ui file 'patient_portal.ui'
#
# Created by: PyQt6 UI code generator 6.6.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from data import DoctorDataProcessor
from iterator import Iterator
from dialog import Dialog


class DoctorUI(QtWidgets.QMainWindow):
    def __init__(self):
        super(DoctorUI, self).__init__()
        self.doctor_data_object = DoctorDataProcessor()
        self.doctor_data_object.load_doctors("health_first_florida.db")
        self.doctors_list = self.doctor_data_object.get_doctors()

    def setup_ui(self, DoctorUI):
        DoctorUI.setObjectName("DoctorUI")
        DoctorUI.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(parent=DoctorUI)
        self.central_widget.setObjectName("central_widget")

        self.frame = QtWidgets.QFrame(parent=self.central_widget)
        self.frame.setGeometry(QtCore.QRect(80, 110, 211, 231))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")

        self._pic_label = QtWidgets.QLabel(parent=self.frame)
        self.load_image("")

        self.form_layout_widget = QtWidgets.QWidget(parent=self.central_widget)
        self.form_layout_widget.setGeometry(QtCore.QRect(330, 110, 391, 231))
        self.form_layout_widget.setObjectName("form_layout_widget")

        self.form_layout = QtWidgets.QFormLayout(self.form_layout_widget)
        self.form_layout.setContentsMargins(0, 0, 0, 0)
        self.form_layout.setObjectName("form_layout")

        self.first_name_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.first_name_label.setObjectName("first_name_label")
        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.first_name_label)
        self.first_name_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.first_name_line_edit.setObjectName("first_name_line_edit")

        self.form_layout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.first_name_line_edit)
        self.last_name_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.last_name_label.setObjectName("last_name_label")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.last_name_label)
        self.last_name_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.last_name_line_edit.setObjectName("last_name_line_edit")
        self.form_layout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.last_name_line_edit)

        self.specialty_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.specialty_label.setObjectName("specialty_label")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.specialty_label)
        self.specialty_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.specialty_line_edit.setObjectName("specialty_line_edit")
        self.form_layout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.specialty_line_edit)

        self.phone_number_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.phone_number_label.setObjectName("phone_number_label")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.phone_number_label)
        self.phone_number_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.phone_number_line_edit.setObjectName("phone_number_line_edit")
        self.form_layout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.phone_number_line_edit)

        self.facility_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.facility_label.setObjectName("facility_label")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.facility_label)
        self.facility_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.facility_line_edit.setObjectName("facility_line_edit")
        self.form_layout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.facility_line_edit)

        self.address_label = QtWidgets.QLabel(parent=self.form_layout_widget)
        self.address_label.setObjectName("address_label")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.address_label)
        self.address_line_edit = QtWidgets.QLineEdit(parent=self.form_layout_widget)
        self.address_line_edit.setObjectName("address_line_edit")
        self.form_layout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.address_line_edit)

        self.previous_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.previous_button.setGeometry(QtCore.QRect(400, 350, 93, 28))
        self.previous_button.setObjectName("previous_button")

        self.next_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.next_button.setGeometry(QtCore.QRect(580, 350, 93, 28))
        self.next_button.setObjectName("next_button")

        self.lineEdit = QtWidgets.QLineEdit(parent=self.central_widget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 681, 22))
        self.lineEdit.setObjectName("lineEdit")

        self.search_button = QtWidgets.QPushButton(parent=self.central_widget)
        self.search_button.setGeometry(QtCore.QRect(700, 10, 93, 28))
        self.search_button.setObjectName("search_button")
        self.search_button.clicked.connect(self.search)

        DoctorUI.setCentralWidget(self.central_widget)

        self.retranslate_ui(DoctorUI)
        QtCore.QMetaObject.connectSlotsByName(DoctorUI)

    def search(self):
        text = self.lineEdit.text().lower()
        search_doctors = []
        for item in self.doctors_list:
            if (text in item.get_name().lower()) or (text in item.get_specialty().lower()) or (text in item.get_information().lower()):
                search_doctors.append(item)
        dialogUI = Dialog()
        dialogUI.setup_ui(dialogUI, search_doctors, text)
        dialogUI.show()
        dialogUI.exec()
        if dialogUI.close:
            self.selected_row = dialogUI.get_selected_row()
            if self.selected_row != None:
                self.output_doctors(self.selected_row, search_doctors)

    def output_doctors(self, selected_row, temp_doctors):
        doctor_iter = Iterator(temp_doctors, selected_row)
        self.set_current_doctor(doctor_iter)
        self.previous_button.clicked.connect(lambda: self.set_previous_doctor(doctor_iter))
        self.next_button.clicked.connect(lambda: self.set_next_doctor(doctor_iter))

    def set_current_doctor(self, iterator):
        temp_doctor = iterator.__next__()
        self.first_name_line_edit.setText(temp_doctor.get_first_name())
        self.last_name_line_edit.setText(temp_doctor.get_last_name())
        self.specialty_line_edit.setText(temp_doctor.get_specialty())
        self.phone_number_line_edit.setText(temp_doctor.get_phone_number())
        self.facility_line_edit.setText(temp_doctor.get_facility())
        self.address_line_edit.setText(temp_doctor.get_address())
        self.load_image(temp_doctor.get_gender())

    def set_next_doctor(self, iterator):
        temp_doctor = iterator.__next__()
        self.first_name_line_edit.setText(temp_doctor.get_first_name())
        self.last_name_line_edit.setText(temp_doctor.get_last_name())
        self.specialty_line_edit.setText(temp_doctor.get_specialty())
        self.phone_number_line_edit.setText(temp_doctor.get_phone_number())
        self.facility_line_edit.setText(temp_doctor.get_facility())
        self.address_line_edit.setText(temp_doctor.get_address())
        self.load_image(temp_doctor.get_gender())

    def set_previous_doctor(self, iterator):
        temp_doctor = iterator.__previous__()
        self.first_name_line_edit.setText(temp_doctor.get_first_name())
        self.last_name_line_edit.setText(temp_doctor.get_last_name())
        self.specialty_line_edit.setText(temp_doctor.get_specialty())
        self.phone_number_line_edit.setText(temp_doctor.get_phone_number())
        self.facility_line_edit.setText(temp_doctor.get_facility())
        self.address_line_edit.setText(temp_doctor.get_address())
        self.load_image(temp_doctor.get_gender())

    def load_image(self, gender=None):
        my_image = QtGui.QImage()
        if gender.lower() == "m":
            my_image.loadFromData(
                self.read_image("male.png"))  # loadFromData also accepts images as a byte-array/string of bytes
        elif gender.lower() == "f":
            my_image.loadFromData(self.read_image("female.png"))
        else:
            my_image.loadFromData(self.read_image(
                "medical.png"))  # choose a parent, such as a layout, or existing label where you want to show your image
        w = 211  # set a value for your scaled width here
        h = 231  # set a value for your scaled height here
        pixmap = QtGui.QPixmap.fromImage(my_image)
        # Scale the image to fit your label
        # It's a good idea to keep the aspect ratio so your image does not get distorted
        scaled_img = pixmap.scaled(w, h, QtCore.Qt.KeepAspectRatio)  # or Qt.IgnoreAspectRatio
        self._pic_label.setPixmap(scaled_img)

    def read_image(self, img_file):
        img_bytes = open(img_file, "rb").read()

        return img_bytes

        # You may also read an image as bytes from the web like so:
        # img_bytes = urllib.request.urlopen(photo_url).read()

    def retranslate_ui(self, DoctorUI):
        _translate = QtCore.QCoreApplication.translate
        DoctorUI.setWindowTitle(_translate("DoctorUI", "DoctorUI"))
        self.first_name_label.setText(_translate("DoctorUI", "First Name"))
        self.last_name_label.setText(_translate("DoctorUI", "Last Name"))
        self.specialty_label.setText(_translate("DoctorUI", "Specialty"))
        self.phone_number_label.setText(_translate("DoctorUI", "Phone Number"))
        self.facility_label.setText(_translate("DoctorUI", "Facility"))
        self.address_label.setText(_translate("DoctorUI", "Address"))
        self.previous_button.setText(_translate("DoctorUI", "<< Previous"))
        self.next_button.setText(_translate("DoctorUI", "Next >>"))
        self.search_button.setText(_translate("DoctorUI", "Search"))
